# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb140dd082b2dcd3fe6602aac9737182998dd645ce513474ca4b5efb592c5af95a328981eae7079ea2d0129d19df29f864c2ae3aed75806b15f22bf5b73b6357

test:
  secret_key_base: 028263a262fbd74d4fd1f5c67498f0d8020d466ba8c4d6535f234de0c5c3c716134cb1200cb9606c30aae6fc031b014ec4dcc4c5e5538b289eb6f5ff24f98701

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
